### ISSUE TITLE
Add support for editing events from multiple organizations

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#416]
UI doesn't currently allow for editing of more than the events of a single organization, regardless of whether the user is an admin in one or several organizations.

The UI should cross-check if the user has the admin-right to any particular event and allow editing accordingly.

Displaying all user-admin-related events in Manage events has already been solved.

**Comment by aleksisalonen** [comment]
Done.

**Comment by Rikuoja** [comment]
The UI still doesn't allow editing events from other than the user's primary organization.

They are listed on the admin list, but the Cancel, Delete and Edit buttons are disabled.

Reopening this issue.

**Comment by aleksisalonen** [comment]
From my testing there looks to be support for editing events from multiple admin organizations, but not for child and affiliate organizations.

The latter are in a way a separate issue, that needs further backend support. But I suppose it needs more frontend work as well?

**Comment by Rikuoja** [comment]
Yes, frontend work is needed to actually understand that the orgs form a hierarchy and check from the backend if the publisher is somewhere under any of the admin organizations in the hierarchy.

**Comment by Rikuoja** [comment]
Probably we need a backend filter `/v1/organization/?child=event_publisher`, which will list parents for a given publisher. Then the UI will know if one of the parents is in the user admin_orgs, and will allow editing.

**Comment by aleksisalonen** [comment]
Support for child and affiliate organizations is a separate issue. This one's ready.
